%% calculate routes from Nth CP to outlet
function allRoutes=outletRoutes(rtable,downstreamCPs)
%OUTLETROUTES Calculates routes from Nth CP to basin outlet
%   Computes the downstream route (CP by CP) from each CP to the
%   basin mouth using the 'rtable' and 'downstream' variables generated by the
%   doRoutingTable.m and getDownstreamCPs.m functions.
%
%   allRoutes=outletRoutes(rtable,downstream)
%
%   Input:  'rtable'        - Routing table comprising the old ID of each CP, its new ID and the IDs of all CPs immediately upstream
%           'downstreamCPs'    - Vector comprising the ID of each CP immediately downstream of Nth CP

%   Output: 'allRoutes'     - Table showing the downstream route (CP by CP) from the Nth CP to the basin outlet.  First column shows the starting CP, subsequent columns show the downstream route
%           
%   By Stephen Dugdale, 2015-04-22

for n=1:size(rtable,1);
list=[];    
nu=1; %set number of upstream CPs to 1   
up=rtable(n,2); %set upstream CP to Nth iteration
while up~=1
list(nu)=up; %append Nth CP to list
up=downstreamCPs(up); %go down from Nth position until end
nu=nu+1; %increment nu on each iteration (this gives the routing distance from Nth CP to outlet
end
allRoutes(n,1:numel(list)+1)=[list,1]; %create list for Nth CP
end

end