%% populate carreauxPartiels and carreauxEntiers structure
function [carreauxPartiels carreauxEntiers]=populateStructs(idCE,iCP,jCP,rtable,pctSurface,downstreamCPs,cumulPctSuperficieCPAmont,iCE,jCE,CPalts,CEalts,CPpctEau,CPpctForet,CPpctMarais,CPpctSolNu,cumulPctForetAmont,cumulPctLacsAmont,cumulPctMaraisAmont,cumulPctSolNuAmont,CEpctForet,CEpctLacRiviere,CEpctMarais,CEpctSolNu)
%POPULATESTRUCTS Populates CP and CE structures with data
%   Populates carreauxPartiels and carreauxEntiers sub-structures of 
%   bassinVersant sub-structure using data generated by
%   CEQUEAU_physiography.m function
%
%   [carreauxPartiels carreauxEntiers]=populateStructs(idCE,iCP,jCP,rtable,pctSurface,downstream,cumulPctSuperficieCPAmont,iCE,jCE,CPalts,CEalts,CPpctEau,CPpctForet,CPpctMarais,CPpctSolNu,cumulPctForetAmont,cumulPctLacsAmont,cumulPctMaraisAmont,cumulPctSolNuAmont,CEpctForet,CEpctLacRiviere,CEpctMarais,CEpctSolNu)
%
%   Input:  'idCE'          - The ID of the CE in which each CP is contained (essentially a new version of 'containingCE' variable)
%           'iCP'           - Vector of i coordinates for CPs
%           'jCP'           - Vector of j coordinates for CPs
%           'rtable'        - New routing table comprising the old ID of each CP, its new ID and the IDs of all CPs immediately upstream
%           'pctSurface'    - Vector of percentage surface areas that each CP contributes to its containing CE
%           'downstreamCPs' - Vector comprising the ID of each CP immediately downstream of Nth CP
%           'cumulPctSuperficieCPAmont'    - Vector of cumulative upstream percentage surface areas that CPs contributes to their containing CEs
%           'iCE'           - Vector of i coordinates for CEs
%           'jCE'           - Vector of i coordinates for CEs
%           'CPalts'        - Vector of altitudes of bottom left coordinate of each CE
%           'CEalts'        - Vector of mean altitudes for each CP
%           'CPpctEau'      - Vector of percentage surface area of each CP covered by water
%           'CPpctForet'    - Vector of percentage surface area of each CP covered by forest
%           'CPpctMarais'   - Vector of percentage surface area of each CP covered by wetlands
%           'CPpctSolNu'    - Vector of percentage surface area of each CP covered by bare soil
%           'cumulPctForetAmont'    - Vector of cumulative upstream percentage surface area that is forest
%           'cumulPctLacsAmont'     - Vector of cumulative upstream percentage surface area that is water
%           'cumulPctMaraisAmont'   - Vector of cumulative upstream percentage surface area that is wetland
%           'cumulPctSolNuAmont'    - Vector of cumulative upstream percentage surface area that is bare soil
%           'CEpctForet'            - Vector of percentage surface area of each CE covered by water
%           'CEpctLacRiviere'       - Vector of percentage surface area of each CE covered by water
%           'CEpctMarais'           - Vector of percentage surface area of each CE covered by water
%           'CEpctSolNu'            - Vector of percentage surface area of each CE covered by water
%
%   Output: 'carreauxPartiels'      - CEQUEAU carreauxPartials sub-structure (to be contained within bassinVersant)
%           'carreauxEntiers'       - CEQUEAU carreauxEntiers sub-structure (to be contained within bassinVersant)
%           
%   By Stephen Dugdale, 2015-04-24

%make rtable n rows * 7 columns
if size(rtable,2)<7;
   rtable(:,end+1)=zeros;
end

%short script that gives the new CP code (ie 65,66,67,68) from each CE
uniqueCE=unique(idCE);
code=zeros(size(idCE));
for n=1:numel(uniqueCE);
    idx=find(idCE==uniqueCE(n));
    code(idx)=65:64+numel(idx);
end

for n=1:size(rtable,1);
    carreauxPartiels(n).i=iCP(n);
    carreauxPartiels(n).j=jCP(n);
    carreauxPartiels(n).code=code(n);
    carreauxPartiels(n).pctSurface=pctSurface(n);
    carreauxPartiels(n).idCPAval=downstreamCPs(n);
    carreauxPartiels(n).idCPsAmont=rtable(n,3:end);
    carreauxPartiels(n).idCE=idCE(n);
    carreauxPartiels(n).pctEau=CPpctEau(n);
    carreauxPartiels(n).pctForet=CPpctForet(n);
    carreauxPartiels(n).pctMarais=CPpctMarais(n);
    carreauxPartiels(n).pctSolNu=CPpctSolNu(n);
    carreauxPartiels(n).altitudeMoy=CPalts(n);
    carreauxPartiels(n).profondeurMin=NaN;
    carreauxPartiels(n).longueurCoursEauPrincipal=NaN;
    carreauxPartiels(n).largeurCoursEauPrincipal=NaN;
    carreauxPartiels(n).penteRiviere=NaN;
    carreauxPartiels(n).cumulPctSuperficieCPAmont=cumulPctSuperficieCPAmont(n);
    carreauxPartiels(n).cumulPctSuperficieLacsAmont=cumulPctLacsAmont(n);
    carreauxPartiels(n).cumulPctSuperficieMaraisAmont=cumulPctMaraisAmont(n);
    carreauxPartiels(n).cumulPctSuperficieForetAmont=cumulPctForetAmont(n);
end

for n=1:numel(iCE);
    carreauxEntiers(n).i=iCE(n);    
    carreauxEntiers(n).j=jCE(n);
    carreauxEntiers(n).pctLacRiviere=CEpctLacRiviere(n);
    carreauxEntiers(n).pctForet=CEpctForet(n);
    carreauxEntiers(n).pctMarais=CEpctMarais(n);
    carreauxEntiers(n).altitude=CEalts(n);
end

end
